### ISSUE TITLE
Why Wire(UInt(3.U)) insteasd of Wire(Uint(3.W))

### ISSUE THREAD

**Issue by EE-LiuYunhao** [jlpteaching/dinocpu-wq20#1]
In the [chisel cheatsheet](https://github.com/jlpteaching/dinocpu-wq20/blob/master/documentation/chisel-notes/cheat-sheet.md) at the [MUX](https://github.com/jlpteaching/dinocpu-wq20/blob/master/documentation/chisel-notes/cheat-sheet.md#muxes) section, a sample program of using one mux is given. 
However, it can be noticed that the creation of x is
```scala
val x = Wire(UInt(3.U))
```
instead of 
```scala
val x = Wire(UInt(3.W))
```
Thus, I am wondering what is the difference between .U and .W? I thought that when we conduct calculation of unsigned numbers, .U is in used and when we are to describe the wire width, the .W is used. However, here to define the width of wire, 3.U is used instead of 3.W.

Is that a typo or does the chisel allow the usage of .U numbers in this scenario?

**Comment by powerjg** [comment]
Yes, this looks like a typo. Thanks for letting us know!

It should be `3.W` because the width of the wire is 3 bits.

**Comment by powerjg** [comment]
@EE-LiuYunhao, please email @JulianToya with your  UC Davis email and he will put this contribution down in our extra credit spreadsheet (see https://github.com/jlpteaching/ECS154B/blob/master/extra-credit.md for details).

Thanks, again!
